// csvBuilder.js — Generates a well-structured CSV report per user

const { getSolution } = require("./errorSolutions");

/**
 * Builds a CSV string for a single user's migration errors
 * @param {string} userEmail
 * @param {Array} errors - array of error objects from ProjectError.csv
 * @param {Object} summary - migration summary data
 * @returns {string} CSV content as string
 */
function buildUserCSV(userEmail, errors, summary = {}) {
  const rows = [];
  const now = new Date().toLocaleString("en-US", {
    year: "numeric", month: "long", day: "numeric",
    hour: "2-digit", minute: "2-digit",
  });

  // ── Section 1: Report Header ──────────────────────────────────────────────
  rows.push(["MIGRATION ERROR REPORT", "", "", "", "", "", ""]);
  rows.push(["Generated on:", now, "", "", "", "", ""]);
  rows.push(["User:", userEmail, "", "", "", "", ""]);
  rows.push(["Source file:", summary.sourceFile || "Migration_summary_report.zip", "", "", "", "", ""]);
  rows.push(["", "", "", "", "", "", ""]);

  // ── Section 2: Summary Stats ──────────────────────────────────────────────
  rows.push(["MIGRATION SUMMARY", "", "", "", "", "", ""]);
  rows.push(["Total files migrated successfully:", summary.filesMigrated || "N/A", "", "", "", "", ""]);
  rows.push(["Total items failed:", errors.length, "", "", "", "", ""]);

  const errorCount = errors.filter(e => getSolution(e.ResultCode).severity === "Error").length;
  const warnCount  = errors.filter(e => getSolution(e.ResultCode).severity === "Warning").length;
  rows.push(["  Errors requiring your action:", errorCount, "", "", "", "", ""]);
  rows.push(["  Warnings (IT will handle):", warnCount, "", "", "", "", ""]);
  rows.push(["", "", "", "", "", "", ""]);

  // ── Section 3: Error Detail Table ─────────────────────────────────────────
  rows.push(["ERROR DETAILS & SOLUTIONS", "", "", "", "", "", ""]);
  rows.push([
    "No.",
    "File / Folder Name",
    "Full Path",
    "Error Code",
    "Error Title",
    "Explanation",
    "Solution",
    "Action Required",
    "IT Will Retry?",
    "Severity",
  ]);

  errors.forEach((err, idx) => {
    const sol = getSolution(err.ResultCode);
    const rawName = err.FullPath ? err.FullPath.split('/').pop() : 'Unknown';
      const fileName = rawName.startsWith('=') || rawName.startsWith('+') || rawName.startsWith('-') ? "'" + rawName : rawName;
      const _unused = err.FullPath
      ? err.FullPath.split("/").pop() || err.FullPath
      : "Unknown";

    rows.push([
      idx + 1,
      fileName,
      err.FullPath || "",
      err.ResultCode || "",
      sol.title,
      sol.explanation,
      sol.solution,
      sol.actionRequired,
      sol.retryByIT,
      sol.severity,
    ]);
  });

  rows.push(["", "", "", "", "", "", ""]);

  // ── Section 4: Next Steps Summary ─────────────────────────────────────────
  rows.push(["YOUR NEXT STEPS", "", "", "", "", "", ""]);

  const userActionItems = errors.filter(
    e => getSolution(e.ResultCode).actionRequired.startsWith("Yes")
  );
  const itRetryItems = errors.filter(
    e => getSolution(e.ResultCode).retryByIT.startsWith("Yes")
  );

  if (userActionItems.length > 0) {
    rows.push([`Items requiring YOUR action (${userActionItems.length}):`, "", "", "", "", "", ""]);
    userActionItems.forEach((err, idx) => {
      const sol = getSolution(err.ResultCode);
      const rawName = err.FullPath ? err.FullPath.split('/').pop() : 'Unknown';
      const fileName = rawName.startsWith('=') || rawName.startsWith('+') || rawName.startsWith('-') ? "'" + rawName : rawName;
      const _unused = err.FullPath ? err.FullPath.split("/").pop() : "Unknown";
      rows.push([`  ${idx + 1}.`, fileName, sol.solution, "", "", "", ""]);
    });
    rows.push(["", "", "", "", "", "", ""]);
  }

  if (itRetryItems.length > 0) {
    rows.push([`Items IT will retry automatically (${itRetryItems.length}):`, "", "", "", "", "", ""]);
    itRetryItems.forEach((err, idx) => {
      const rawName = err.FullPath ? err.FullPath.split('/').pop() : 'Unknown';
      const fileName = rawName.startsWith('=') || rawName.startsWith('+') || rawName.startsWith('-') ? "'" + rawName : rawName;
      const _unused = err.FullPath ? err.FullPath.split("/").pop() : "Unknown";
      rows.push([`  ${idx + 1}.`, fileName, "IT will retry within 48 hours — no action needed", "", "", "", ""]);
    });
    rows.push(["", "", "", "", "", "", ""]);
  }

  // ── Section 5: Footer ─────────────────────────────────────────────────────
  rows.push(["CONTACT", "", "", "", "", "", ""]);
  rows.push(["For assistance contact:", "it-support@chs.net", "", "", "", "", ""]);
  rows.push(["IT Migration Team", "CHSPSC LLC", "", "", "", "", ""]);
  rows.push(["", "", "", "", "", "", ""]);
  rows.push(["This report was auto-generated by the CHSPSC IT Migration System.", "", "", "", "", "", ""]);

  return rowsToCSV(rows);
}

/**
 * Converts array of row arrays to properly escaped CSV string
 */
function rowsToCSV(rows) {
  return rows
    .map(row =>
      row
        .map(cell => {
          const str = String(cell === null || cell === undefined ? "" : cell);
          // Escape double quotes and wrap in quotes if needed
          if (str.includes(",") || str.includes('"') || str.includes("\n") || str.includes("\r")) {
            return `"${str.replace(/"/g, '""')}"`;
          }
          return str;
        })
        .join(",")
    )
    .join("\r\n");
}

module.exports = { buildUserCSV };
